# Part 1 - Word2Vec

In [44]:
import nltk


texts = [
    "AI is changing the world",
    "Machine learning is amazing",
    "Deep learning powers many applications",
    "I enjoy learning NLP",
    "NLP is fun and useful"
]

tokens = [nltk.word_tokenize(text) for text in texts]
print(tokens)


[['AI', 'is', 'changing', 'the', 'world'], ['Machine', 'learning', 'is', 'amazing'], ['Deep', 'learning', 'powers', 'many', 'applications'], ['I', 'enjoy', 'learning', 'NLP'], ['NLP', 'is', 'fun', 'and', 'useful']]


## Task1
 Train a Word2Vec model using vector_size=30, window=2, min_count=1.

In [45]:
from gensim.models import Word2Vec

model = Word2Vec(tokens, vector_size=50, window=3, min_count=1)


## Task2
 Find the number of unique words and identify the most frequent word without printing the entire vocabulary.

In [46]:
number_of_unique_words = len(model.wv)
print("Number of unique words: ", number_of_unique_words)

most_frequent_word = model.wv.index_to_key[0]
print("Most frequent word: ", most_frequent_word)

Number of unique words:  18
Most frequent word:  learning


## Task3
 Print the word vectors of any two words of your choice.

In [47]:
# word1 'NLP'
print('word vector for word "NLP": ',model.wv['NLP'])

# word2 'and'
print('word vector for word "and":',model.wv['and'])

word vector for word "NLP":  [-0.01723938  0.00733148  0.01037977  0.01148388  0.01493384 -0.01233535
  0.00221123  0.01209456 -0.0056801  -0.01234705 -0.00082045 -0.0167379
 -0.01120002  0.01420908  0.00670508  0.01445134  0.01360049  0.01506148
 -0.00757831 -0.00112361  0.00469675 -0.00903806  0.01677746 -0.01971633
  0.01352928  0.00582883 -0.00986566  0.00879638 -0.00347915  0.01342277
  0.0199297  -0.00872489 -0.00119868 -0.01139127  0.00770164  0.00557325
  0.01378215  0.01220219  0.01907699  0.01854683  0.01579614 -0.01397901
 -0.01831173 -0.00071151 -0.00619968  0.01578863  0.01187715 -0.00309133
  0.00302193  0.00358008]
word vector for word "and": [ 0.00018913  0.00615464 -0.01362529 -0.00275093  0.01533716  0.01469282
 -0.00734659  0.0052854  -0.01663426  0.01241097 -0.00927464 -0.00632821
  0.01862271  0.00174677  0.01498141 -0.01214813  0.01032101  0.01984565
 -0.01691478 -0.01027138 -0.01412967 -0.0097253  -0.00755713 -0.0170724
  0.01591121 -0.00968788  0.01684723  0.010

## Task4
 Find the two most similar words to "learning".

In [48]:
similar_words = model.wv.similar_by_word('learning', topn=2)

print(similar_words)

[('world', 0.21057100594043732), ('Deep', 0.16704076528549194)]


## Task5
 Choose any two pairs of words, calculate their similarity, and briefly explain the results.

 explain the results:
  Cosine Similarity Scale: Values range from $-1.0$  to $1.0$.

  Machine vs. learning ($sim_1$) High/Positive Similarity  -> 0.15019882

  enjoy vs. NLP ($sim_2$)Lower Similarity -> 0.08872843

In [49]:
pair1 = ['Machine', 'learning']
pair2 = ['enjoy', 'NLP']

sim1 = model.wv.similarity(pair1[0],pair1[1])
sim2 = model.wv.similarity(pair2[0],pair2[1])

print('Similarity between "Machine", "learning": ', sim1)
print('Similarity between "enjoy", "NLP": ', sim2)

Similarity between "Machine", "learning":  0.15019882
Similarity between "enjoy", "NLP":  0.08872843


# Part 2 - Simple RNN

In [50]:
texts = [
    "I love AI",
    "AI is amazing",
    "I hate bugs",
    "Coding is fun",
    "This movie is terrible",
    "This movie is great"
]

labels = [1, 1, 0, 1, 0, 1]

## Task1
 Convert the text into sequences using TensorFlow Tokenizer and print only the sequences.

In [51]:
from tensorflow.keras.preprocessing.text import Tokenizer
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)
print('word_index: ',tokenizer.word_index)

sequences = tokenizer.texts_to_sequences(texts)
print('texts_to_sequences: ',sequences)

word_index:  {'is': 1, 'i': 2, 'ai': 3, 'this': 4, 'movie': 5, 'love': 6, 'amazing': 7, 'hate': 8, 'bugs': 9, 'coding': 10, 'fun': 11, 'terrible': 12, 'great': 13}
texts_to_sequences:  [[2, 6, 3], [3, 1, 7], [2, 8, 9], [10, 1, 11], [4, 5, 1, 12], [4, 5, 1, 13]]


## Task2
  Pad all sequences to the maximum sentence length in the dataset.

In [52]:
pad = pad_sequences(
    sequences,
    maxlen=5,
    padding='post'
    
)
print(pad)

[[ 2  6  3  0  0]
 [ 3  1  7  0  0]
 [ 2  8  9  0  0]
 [10  1 11  0  0]
 [ 4  5  1 12  0]
 [ 4  5  1 13  0]]


## Task3
 Build a model with Embedding, SimpleRNN, and Dense output layers. Choose the embedding dimension and the number of RNN units yourself.

In [53]:
vocab_size = len(tokenizer.word_index) + 1

model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=8, input_length=5),
    SimpleRNN(units=16),
    Dense(1, activation="sigmoid")
])

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


## Task4
Train the model for 15 epochs.

In [54]:
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

history = model.fit(
    pad,
    np.array(labels),
    epochs=15,
    verbose=1
)

Epoch 1/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.6667 - loss: 0.6880
Epoch 2/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.6667 - loss: 0.6828
Epoch 3/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.8333 - loss: 0.6776
Epoch 4/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.8333 - loss: 0.6724
Epoch 5/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.8333 - loss: 0.6672
Epoch 6/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.8333 - loss: 0.6620
Epoch 7/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.8333 - loss: 0.6567
Epoch 8/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6667 - loss: 0.6514
Epoch 9/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.6667 - loss: 0.6461
Epoch 10/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6667 - loss: 0.6407
Epoch 11/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6667 - loss: 0.6352
Epoch 12/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6667 - loss: 0.6297
Epo

## Task5
 Predict the sentiment of any two new sentences of your choice and explain whether the predictions are reasonable.

In [55]:
test_sentences = [
    "movie is amazing", 
    "hate bugs"
]

test_seq = tokenizer.texts_to_sequences(test_sentences)
test_padded = pad_sequences(test_seq, maxlen=5, padding='post')

predictions = model.predict(test_padded)
print(predictions)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step
[[0.58752584]
 [0.5689584 ]]


## Bonus Challenge
Modify only one of the following: vector_size, window, embedding dimension, or the number of RNN units. Retrain the model and briefly describe any observed changes.


In [56]:
model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=8, input_length=5),
    SimpleRNN(units=32),
    Dense(1, activation="sigmoid")
])

model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
model.fit(pad, np.array(labels), epochs=15, verbose=0)

c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\embedding.py:103: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
