Tokenizer

In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer

texts = [
    "I love NLP",
    "I love Machine Learning",
    "Deep Learning is amazing"
]

tokenizer = Tokenizer()

tokenizer.fit_on_texts(texts)

print(tokenizer.word_index)

{'i': 1, 'love': 2, 'learning': 3, 'nlp': 4, 'machine': 5, 'deep': 6, 'is': 7, 'amazing': 8}


# Convert Text to Sequences

In [2]:
sequences = tokenizer.texts_to_sequences(texts)

print(sequences)

[[1, 2, 4], [1, 2, 5, 3], [6, 3, 7, 8]]


# Padding

In [3]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded = pad_sequences(
    sequences,
    maxlen=6,
    padding="post"
)

print(padded)

[[1 2 4 0 0 0]
 [1 2 5 3 0 0]
 [6 3 7 8 0 0]]


# Simple Data set

In [4]:
texts = [
    "good movie",
    "excellent film",
    "awesome movie",
    "bad movie",
    "terrible film",
    "worst movie"
]

labels = [1,1,1,0,0,0]

Tokenizer

In [5]:
tokenizer = Tokenizer()

tokenizer.fit_on_texts(texts)

sequences = tokenizer.texts_to_sequences(texts)

X = pad_sequences(sequences,maxlen=2)

print(X)

[[3 1]
 [4 2]
 [5 1]
 [6 1]
 [7 2]
 [8 1]]


# Build RNN

In [6]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,SimpleRNN,Dense

model = Sequential()

model.add(
    Embedding(
        input_dim=20,
        output_dim=8,
        input_length=2
    )
)

model.add(SimpleRNN(16))

model.add(Dense(1,activation="sigmoid"))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [7]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [10]:
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

In [11]:
import numpy as np

model.fit(
    X,
    np.array(labels),
    epochs=30,
    verbose=1
)

Epoch 1/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.8333 - loss: 0.6802
Epoch 2/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8333 - loss: 0.6777
Epoch 3/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.8333 - loss: 0.6752
Epoch 4/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 1.0000 - loss: 0.6726
Epoch 5/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 1.0000 - loss: 0.6700
Epoch 6/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 1.0000 - loss: 0.6673
Epoch 7/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.6646
Epoch 8/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.6618
Epoch 9/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.6589
Epoch 10/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.6559
Epoch 11/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 1.0000 - loss: 0.6529
Epoch 12/30
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 1.0000 - loss: 0.6498
Epo

Prediction

In [12]:
test = tokenizer.texts_to_sequences(
    ["good film"]
)

test = pad_sequences(test,maxlen=2)

prediction = model.predict(test)

print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 244ms/step
[[0.58457386]]


In [13]:
test = tokenizer.texts_to_sequences(
    ["worst film"]
)

test = pad_sequences(test,maxlen=2)

prediction = model.predict(test)

print(prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step
[[0.43569937]]


# word 2 vec

In [15]:
!pip install gensim

from gensim.models import Word2Vec

sentences = [
    ["i", "love", "nlp"],
    ["deep", "learning", "is", "fun"],
    ["nlp", "is", "awesome"]
]

model = Word2Vec(sentences, vector_size=50, window=3, min_count=1)

print(model.wv["nlp"])

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 49.9 MB/s eta 0:00:00
[-0.01631583  0.0089916  -0.00827415  0.00164907  0.01699724 -0.00892435
  0.009035   -0.01357392 -0.00709698  0.01879702 -0.00315531  0.00064274
 -0.00828126 -0.01536538 -0.00301602  0.00493959 -0.00177605  0.01106732
 -0.00548595  0.00452013  0.01091159  0.01669191 -0.00290748 -0.01841629
  0.0087411   0.00114357  0.01488382 -0.00162657 -0.00527683 -0.01750602
 -0.00171311  0.00565313  0.01080286  0.01410531 -0.01140624  0.00371764
  0.01217773 -0.0095961  -0.00621452  0.01359526  0.00326295  0.00037983
  0.00694727  0.00043555  0.01923765  0.01012121 -0.01783478 -0.01408312
  0.00180291  0.01278507]
